name: project
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - matplotlib
  - scikit-learn
  - opencv 
  - ipykernel
  - jupyterlab
  - tqdm
  - scikit-image
  - pip
  - pip:
      - keras
      - albumentations
      - einops
      - shapely
      - absl-py
      - torch
      - torchvision
      - ultralytics
      - timm
      - mamba-ssm #pip install git+https://github.com/state-spaces/mamba.git --no-build-isolation
      - nibabel
      - yacs
      - dynamic-network-architectures
